version: "2"
services:
  master:
    image: eeacms/jenkins-master
    ports:
    - "80:8080"
    environment:
    - JAVA_OPTS=-Xmx2048m
    volumes:
    - jenkins-master:/var/jenkins_home

  worker:
    image: eeacms/jenkins-slave
    environment:
      JAVA_OPTS: "-Xmx2048m"
      JENKINS_MASTER: "http://master:8080"
      JENKINS_NAME: "worker"
      JENKINS_USER: "jenkins"
      JENKINS_PASS: "jenkins"
      JENKINS_RETRY: "10"
    volumes:
    - jenkins-worker:/var/jenkins_home/worker

volumes:
  jenkins-master:
  jenkins-worker:
